### ISSUE TITLE
Reference for AAMVA 2016 AAMVA DL/ID Card Design Standard Personal Identification – AAMVA North American Standard

### ISSUE THREAD

**Issue by christopherlrogers** [stephenquan/AAMVAtoJSON#2]
2016 - AAMVA DL/ID Card Design Standard
Personal Identification – AAMVA North American Standard

[https://www.aamva.org/2016carddesignstandard/](url)
[AAMVA 2016 DL-ID North American Card Design Standard.pdf](https://github.com/stephenquan/AAMVAtoJSON/files/3291465/AAMVA.2016.DL-ID.North.American.Card.Design.Standard.pdf)

**Comment by stephenquan** [comment]
Thanks for the reference, I've added it to the README
