### ISSUE TITLE
Return Obj as JSON String for Use in Survey123

### ISSUE THREAD

**Issue by christopherlrogers** [stephenquan/AAMVAtoJSON#3]
Hey Stephen,

I have modified the object return in my iteration to return a JSON String for use in Survey123 rather than just an Object. Not sure if this is absolutely required but it was the only way for to easily parse through the Obj and obtain the parts to autofill my form(s).

return JSON.stringify(obj);

Thanks for the updates on the Date/Time and the ability to differ between USA and CAN DL's it is working great!

Regards,
Chris Rogers

**Comment by stephenquan** [comment]
@christopherlrogers I checked in a bunch of changes:

 - Refactor to use ECMAScript 6 spec as per #4 
 - Then, I added a format options and default to string, as you say, to suit Survey123 better
